version: '3.8'

services:
  db:
    image: postgres:15-alpine
    container_name: incomm-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: in_commodities
    ports:
      - "5432:5432"
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  # This is your Python worker/API
  app:
    build: .
    container_name: incomm-app
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    volumes:
      - ./src:/app/src
      - ./tests:/app/tests
      - ./sql:/app/sql
      - ./trades.csv:/app/trades.csv
      - ./test_trades.csv:/app/test_trades.csv
    environment:
      - PYTHONPATH=/app
    command: >
      sh -c "python src/ingest.py && python src/reconcile.py"